### PR TITLE
GEN-126: Migrate hCore from Webpack 4 to Vite

### PR DESCRIPTION
**Pull request by judeallred**
I was having trouble adding in modern libraries, such as oktokit, without hitting lots of babel and webpack-induced hurdles.  By switching to vite, we stop using webpack and babel for 'core', instead making use of vite's defaults. 

This review is still a draft--  While the site is online, there's some sort of communication problem with the web workers where they won't start/stop simulations (however single steps work fine).  Additionally the 'build' step fails with an OOM error on my computer... this might be resolved by a bigger computer, or ideally by a smarter build config.

### CODE REVIEW

**Comment by judeallred** [comment]
I've got the build sorted now, now just need to sort out what's up with the web workers.

**Comment by judeallred** [comment]
I've pulled in some foundational upgrades that make this significantly easier to work on.

- We had a ton of typescript compile errors, and weren't even running tsc.  That's no more, I fixed (or disabled) them all and brought 'tsc' into the lint check, so the build has to pass before people can push.
- I updated to modern lint rules, as recommended by Vite.  our eslint and prettier config is now at tip.
- the modern recommended rules are now in place, whereever possible.
- Turned on prettier caching to save a bunch of time.
- renamed yarn's 'fmt-check' to 'lint'
- fixed a bunch of type bugs in typescript.
- our redux types are all confused; I sequestered them away but they should all be fixed up in order for us to use redux with types.
- the 'custom build directory' stuff has all been ripped out. we don't need it anymore and can restore it if we care.
- webpack is mostly gone, but lingers on as a build runner for jest.
- lots of package.json removals and version upgrades
- upgraded typescript to the latest minor version beneath its major

**Comment by judeallred** [comment]
PR todos:
  - fix the vercel deployment
  - further testing on the web workers

**Comment by judeallred** [comment]
Promoted out of draft mode-- I've got core back to its functionality, but now without a huge amount of aged cruft.

I haven't looked at the Vercel build yet. @CiaranMn if you could take a glance at that I'd be appreciative.

**Comment by judeallred** [comment]
Vercel should be fixed.  Will return to this and give myself a self-review, then it can merge.

**Review by judeallred — COMMENTED** [review]
Completed self-review, PR is ready to merge

**Comment by nonparibus** [comment]
🎉 Awesome work, thanks Jude!

**Review by vilkinsons — APPROVED** [review]

**Pull request merged**
